# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('date_created', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('descripion', models.TextField()),
                ('nasa_id', models.CharField(max_length=50)),
            ],
        ),
    ]
